### ISSUE TITLE
[BUG] Backup SUPER Partition

### ISSUE THREAD

**Issue by xAffan** [boedhack99/device_xiaomi_spes-TWRP#3]
The super partition consisting of system,vendor,systemext,product fails to backup if the backup is being done to external SD card while it succeeds if the backup is being done to internal storage. It fails at around 50% when being backed up to SD card. I have attached log and screenshot of it. Thanks #
![Screenshot_2022-04-07-21-55-04](https://user-images.githubusercontent.com/59138135/162257268-dd69edbd-458d-40fa-8997-bc65088777e8.png)
[recovery.log](https://github.com/boedhack99/device_xiaomi_spes-TWRP/files/8445093/recovery.log)

**Comment by xAffan** [comment]
Reading the recovery.log, here is the exact point of error. 
![Screenshot_2022-04-07-22-07-33-875_nextapp fx](https://user-images.githubusercontent.com/59138135/162258806-78e950f8-5ca6-4281-bc2d-20104e1add54.jpg)

**Comment by boedhack99** [comment]
For now twrp doesn't work to backup dynamically partitions
