### ISSUE TITLE
[BUG] Stock theme version 

### ISSUE THREAD

**Issue by xAffan** [boedhack99/device_xiaomi_spes-TWRP#5]
Although relatively harmless, TWRP throws a warning that the stock theme version is wrong. It is set 0, as indicated in logs while it should be 5. I'm talking about the "theme version" in the xml files of the theme.

**Comment by boedhack99** [comment]
Theming on twrp for what,i think for now i no need theme

**Comment by xAffan** [comment]
It's not a theme thing, it's just warning. Stock theme that is included by default in TWRP, it's version should be set to 5
